#!/bin/python3
import random
X = (random.randint(0, 9))
Y = (random.randint(0, 9))
W = (random.randint(0, 9))
Z = (random.randint(0, 9))

Cards=[(X), (Y), (W), (Z)]
print (Cards)
for i in range (0, 4):
    print ()
    print (Cards[(i)])
    print ()

